- table: user
  attr:
    - name: id
      type: S
    - name: email
      type: S
    - name: createdAt
      type: 'N'
  key:
    - name: id
      type: HASH
    - name: createdAt
      type: RANGE
  provisioned:
    read: 5
    write: 5
  globalIndex:
    - name: emailIndex
      key:
        - name: email
          type: HASH
      projection:
        type: ALL #KEYS_ONLY,INCLUDE,ALL
      provisioned:
        read: 5
        write: 5

- table: profile
  attr:
    - name: id
      type: S
  key:
    - name: id
      type: HASH
  provisioned:
    read: 5
    write: 5


